require "Items/SuburbsDistributions"
require "Items/ProceduralDistributions"
require "Vehicles/VehicleDistributions"

--[****************************** RESEARCH ITEMS ******************************]--

--[------------------- HTFACMicroscope -------------------]--
table.insert(ProceduralDistributions.list["GigamartSchool"].items, "HTFAC.HTFACMicroscope")
table.insert(ProceduralDistributions.list["GigamartSchool"].items, 0.1)
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, "HTFAC.HTFACMicroscope")
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, 0.1)
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "HTFAC.HTFACMicroscope")
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.1)

--[------------------- HTFACChemistrySet -------------------]--
table.insert(ProceduralDistributions.list["StoreShelfMedical"].items, "HTFAC.HTFACChemistrySet1")
table.insert(ProceduralDistributions.list["StoreShelfMedical"].items, 3)
table.insert(ProceduralDistributions.list["StoreShelfMedical"].items, "HTFAC.HTFACChemistrySet2")
table.insert(ProceduralDistributions.list["StoreShelfMedical"].items, 3)
table.insert(ProceduralDistributions.list["StoreShelfMedical"].items, "HTFAC.HTFACChemistrySet3")
table.insert(ProceduralDistributions.list["StoreShelfMedical"].items, 3)

table.insert(ProceduralDistributions.list["ClassroomDesk"].items, "HTFAC.HTFACChemistrySet1")
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, 0.01)
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, "HTFAC.HTFACChemistrySet2")
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, 0.01)
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, "HTFAC.HTFACChemistrySet3")
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, 0.01)

table.insert(ProceduralDistributions.list["ClassroomMisc"].items, "HTFAC.HTFACChemistrySet1")
table.insert(ProceduralDistributions.list["ClassroomMisc"].items, 2)
table.insert(ProceduralDistributions.list["ClassroomMisc"].items, "HTFAC.HTFACChemistrySet2")
table.insert(ProceduralDistributions.list["ClassroomMisc"].items, 2)
table.insert(ProceduralDistributions.list["ClassroomMisc"].items, "HTFAC.HTFACChemistrySet3")
table.insert(ProceduralDistributions.list["ClassroomMisc"].items, 2)

table.insert(ProceduralDistributions.list["ClassroomShelves"].items, "HTFAC.HTFACChemistrySet1")
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, 3)
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, "HTFAC.HTFACChemistrySet2")
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, 3)
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, "HTFAC.HTFACChemistrySet3")
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, 3)

table.insert(ProceduralDistributions.list["CrateToys"].items, "HTFAC.HTFACChemistrySet1")
table.insert(ProceduralDistributions.list["CrateToys"].items, 3)
table.insert(ProceduralDistributions.list["CrateToys"].items, "HTFAC.HTFACChemistrySet2")
table.insert(ProceduralDistributions.list["CrateToys"].items, 3)
table.insert(ProceduralDistributions.list["CrateToys"].items, "HTFAC.HTFACChemistrySet3")
table.insert(ProceduralDistributions.list["CrateToys"].items, 3)

table.insert(ProceduralDistributions.list["GigamartToys"].items, "HTFAC.HTFACChemistrySet1")
table.insert(ProceduralDistributions.list["GigamartToys"].items, 3)
table.insert(ProceduralDistributions.list["GigamartToys"].items, "HTFAC.HTFACChemistrySet2")
table.insert(ProceduralDistributions.list["GigamartToys"].items, 3)
table.insert(ProceduralDistributions.list["GigamartToys"].items, "HTFAC.HTFACChemistrySet3")
table.insert(ProceduralDistributions.list["GigamartToys"].items, 3)

table.insert(ProceduralDistributions.list["GigamartSchool"].items, "HTFAC.HTFACChemistrySet1")
table.insert(ProceduralDistributions.list["GigamartSchool"].items, 3)
table.insert(ProceduralDistributions.list["GigamartSchool"].items, "HTFAC.HTFACChemistrySet2")
table.insert(ProceduralDistributions.list["GigamartSchool"].items, 3)
table.insert(ProceduralDistributions.list["GigamartSchool"].items, "HTFAC.HTFACChemistrySet3")
table.insert(ProceduralDistributions.list["GigamartSchool"].items, 3)

table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "HTFAC.HTFACChemistrySet1")
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.1)
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "HTFAC.HTFACChemistrySet2")
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.1)
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "HTFAC.HTFACChemistrySet3")
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.1)

table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "HTFAC.HTFACChemistrySet1")
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.1)
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "HTFAC.HTFACChemistrySet2")
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.1)
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "HTFAC.HTFACChemistrySet3")
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.1)


--[****************************** INJECTORS ******************************]--

--[------------------- HTFACInjectorEmpty -------------------]--
table.insert(ProceduralDistributions.list["MedicalClinicTools"].items, "HTFAC.HTFACInjectorEmpty")
table.insert(ProceduralDistributions.list["MedicalClinicTools"].items, 10)
table.insert(ProceduralDistributions.list["MedicalStorageTools"].items, "HTFAC.HTFACInjectorEmpty")
table.insert(ProceduralDistributions.list["MedicalStorageTools"].items, 10)
table.insert(ProceduralDistributions.list["SafehouseMedical"].items, "HTFAC.HTFACInjectorEmpty")
table.insert(ProceduralDistributions.list["SafehouseMedical"].items, 5)
table.insert(ProceduralDistributions.list["ArmyStorageMedical"].items, "HTFAC.HTFACInjectorEmpty")
table.insert(ProceduralDistributions.list["ArmyStorageMedical"].items, 10)
table.insert(VehicleDistributions["DoctorTruckBed"].items, "HTFAC.HTFACInjectorEmpty")
table.insert(VehicleDistributions["DoctorTruckBed"].items, 10)
table.insert(SuburbsDistributions["FirstAidKit"].items, "Base.HTFACInjectorEmpty")
table.insert(SuburbsDistributions["FirstAidKit"].items, 10)

--[------------------- HTFACInjectorUsed -------------------]--
table.insert(ProceduralDistributions.list["BathroomCabinet"].items, "HTFAC.HTFACInjectorUsed")
table.insert(ProceduralDistributions.list["BathroomCabinet"].items, 2)
table.insert(ProceduralDistributions.list["BathroomCounter"].items, "HTFAC.HTFACInjectorUsed")
table.insert(ProceduralDistributions.list["BathroomCounter"].items, 2)
table.insert(ProceduralDistributions.list["BathroomCounterEmpty"].items, "HTFAC.HTFACInjectorUsed")
table.insert(ProceduralDistributions.list["BathroomCounterEmpty"].items, 0.25)
table.insert(ProceduralDistributions.list["SafehouseMedical"].items, "HTFAC.HTFACInjectorUsed")
table.insert(ProceduralDistributions.list["SafehouseMedical"].items, 2)


--[****************************** PACKS ******************************]--

--[------------------- HTFACPackInjectors -------------------]--
table.insert(ProceduralDistributions.list["MedicalClinicTools"].items, "HTFAC.HTFACPackInjectors")
table.insert(ProceduralDistributions.list["MedicalClinicTools"].items, 10)
table.insert(ProceduralDistributions.list["MedicalStorageTools"].items, "HTFAC.HTFACPackInjectors")
table.insert(ProceduralDistributions.list["MedicalStorageTools"].items, 10)
table.insert(ProceduralDistributions.list["StoreShelfMedical"].items, "HTFAC.HTFACPackInjectors")
table.insert(ProceduralDistributions.list["StoreShelfMedical"].items, 10)
table.insert(ProceduralDistributions.list["SafehouseMedical"].items, "HTFAC.HTFACPackInjectors")
table.insert(ProceduralDistributions.list["SafehouseMedical"].items, 5)
table.insert(ProceduralDistributions.list["ArmyStorageMedical"].items, "HTFAC.HTFACPackInjectors")
table.insert(ProceduralDistributions.list["ArmyStorageMedical"].items, 10)
table.insert(VehicleDistributions["DoctorTruckBed"].items, "HTFAC.HTFACPackInjectors")
table.insert(VehicleDistributions["DoctorTruckBed"].items, 10)

--[------------------- HTFACPackTestTubes -------------------]--
table.insert(ProceduralDistributions.list["MedicalClinicTools"].items, "HTFAC.HTFACPackTestTubes")
table.insert(ProceduralDistributions.list["MedicalClinicTools"].items, 10)
table.insert(ProceduralDistributions.list["MedicalStorageTools"].items, "HTFAC.HTFACPackTestTubes")
table.insert(ProceduralDistributions.list["MedicalStorageTools"].items, 10)
table.insert(ProceduralDistributions.list["StoreShelfMedical"].items, "HTFAC.HTFACPackTestTubes")
table.insert(ProceduralDistributions.list["StoreShelfMedical"].items, 10)
table.insert(ProceduralDistributions.list["SafehouseMedical"].items, "HTFAC.HTFACPackTestTubes")
table.insert(ProceduralDistributions.list["SafehouseMedical"].items, 5)
table.insert(ProceduralDistributions.list["ArmyStorageMedical"].items, "HTFAC.HTFACPackTestTubes")
table.insert(ProceduralDistributions.list["ArmyStorageMedical"].items, 10)
table.insert(ProceduralDistributions.list["ClassroomMisc"].items, "HTFAC.HTFACPackTestTubes")
table.insert(ProceduralDistributions.list["ClassroomMisc"].items, 1)
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, "HTFAC.HTFACPackTestTubes")
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, 1)


--[****************************** CONSUMEABLES ******************************]--

--[------------------- HTFACPackCottonSwabs -------------------]--
table.insert(ProceduralDistributions.list["MedicalClinicTools"].items, "HTFAC.HTFACPackCottonSwabs")
table.insert(ProceduralDistributions.list["MedicalClinicTools"].items, 4)
table.insert(ProceduralDistributions.list["MedicalStorageTools"].items, "HTFAC.HTFACPackCottonSwabs")
table.insert(ProceduralDistributions.list["MedicalStorageTools"].items, 4)
table.insert(ProceduralDistributions.list["StoreShelfMedical"].items, "HTFAC.HTFACPackCottonSwabs")
table.insert(ProceduralDistributions.list["StoreShelfMedical"].items, 10)
table.insert(ProceduralDistributions.list["SafehouseMedical"].items, "HTFAC.HTFACPackCottonSwabs")
table.insert(ProceduralDistributions.list["SafehouseMedical"].items, 4)
table.insert(ProceduralDistributions.list["ArmyStorageMedical"].items, "HTFAC.HTFACPackCottonSwabs")
table.insert(ProceduralDistributions.list["ArmyStorageMedical"].items, 4)
table.insert(ProceduralDistributions.list["BathroomCabinet"].items, "HTFAC.HTFACPackCottonSwabs")
table.insert(ProceduralDistributions.list["BathroomCabinet"].items, 10)
table.insert(ProceduralDistributions.list["BathroomCounter"].items, "HTFAC.HTFACPackCottonSwabs")
table.insert(ProceduralDistributions.list["BathroomCounter"].items, 10)
table.insert(ProceduralDistributions.list["ClassroomMisc"].items, "HTFAC.HTFACPackCottonSwabs")
table.insert(ProceduralDistributions.list["ClassroomMisc"].items, 1)
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, "HTFAC.HTFACPackCottonSwabs")
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, 1)
table.insert(VehicleDistributions["DoctorTruckBed"].items, "HTFAC.HTFACPackCottonSwabs")
table.insert(VehicleDistributions["DoctorTruckBed"].items, 10)
table.insert(SuburbsDistributions["FirstAidKit"].items, "Base.HTFACPackCottonSwabs")
table.insert(SuburbsDistributions["FirstAidKit"].items, 10)

--[------------------- HTFACChemicals -------------------]--
table.insert(ProceduralDistributions.list["CrateFarming"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["CrateFarming"].items, 4)
table.insert(ProceduralDistributions.list["GardenStoreMisc"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["GardenStoreMisc"].items, 4)
table.insert(ProceduralDistributions.list["ToolStoreFarming"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["ToolStoreFarming"].items, 1)
table.insert(ProceduralDistributions.list["ToolStoreMisc"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["ToolStoreMisc"].items, 1)
table.insert(ProceduralDistributions.list["StoreCounterCleaning"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["StoreCounterCleaning"].items, 1)
table.insert(ProceduralDistributions.list["MedicalClinicDrugs"].items, "HTFACHC.HTFACChemicals")
table.insert(ProceduralDistributions.list["MedicalClinicDrugs"].items, 4)
table.insert(ProceduralDistributions.list["MedicalClinicTools"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["MedicalClinicTools"].items, 4)
table.insert(ProceduralDistributions.list["MedicalStorageDrugs"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["MedicalStorageDrugs"].items, 4)
table.insert(ProceduralDistributions.list["MedicalStorageTools"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["MedicalStorageTools"].items, 4)
table.insert(ProceduralDistributions.list["StoreShelfMedical"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["StoreShelfMedical"].items, 15)
table.insert(ProceduralDistributions.list["SafehouseMedical"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["SafehouseMedical"].items, 5)
table.insert(ProceduralDistributions.list["ArmyStorageMedical"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["ArmyStorageMedical"].items, 15)
table.insert(ProceduralDistributions.list["JanitorChemicals"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["JanitorChemicals"].items, 10)
table.insert(ProceduralDistributions.list["JanitorCleaning"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["JanitorCleaning"].items, 10)
table.insert(ProceduralDistributions.list["JanitorMisc"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["JanitorMisc"].items, 8)
table.insert(ProceduralDistributions.list["ClassroomMisc"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["ClassroomMisc"].items, 1)
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, "HTFAC.HTFACChemicals")
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, 1)


--[****************************** LITERATURE ******************************]--

--[------------------- HTFACLiteratureChemistry101 -------------------]--
--For some reason this doesn't seem to work.
--table.insert(VehicleDistributions["Postal"].items, "HTFAC.HTFACLiteratureChemistry101")
--table.insert(VehicleDistributions["Postal"].items, 0.5)
table.insert(ProceduralDistributions.list["ClassroomMisc"].items, "HTFAC.HTFACLiteratureChemistry101")
table.insert(ProceduralDistributions.list["ClassroomMisc"].items, 0.5)
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, "HTFAC.HTFACLiteratureChemistry101")
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, 0.5)
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, "HTFAC.HTFACLiteratureChemistry101")
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, 0.1)
table.insert(ProceduralDistributions.list["CrateBooks"].items, "HTFAC.HTFACLiteratureChemistry101")
table.insert(ProceduralDistributions.list["CrateBooks"].items, 1)
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "HTFAC.HTFACLiteratureChemistry101")
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 2)
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "HTFAC.HTFACLiteratureChemistry101")
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 1)
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "HTFAC.HTFACLiteratureChemistry101")
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.1)
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "HTFAC.HTFACLiteratureChemistry101")
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.1)
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "HTFAC.HTFACLiteratureChemistry101")
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 0.5)

--[------------------- HTFACLiteratureMicrobiology -------------------]--
--For some reason this doesn't seem to work.
--table.insert(VehicleDistributions["Postal"].items, "HTFAC.HTFACLiteratureMicrobiology")
--table.insert(VehicleDistributions["Postal"].items, 0.5)
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "HTFAC.HTFACLiteratureMicrobiology")
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1)
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "HTFAC.HTFACLiteratureMicrobiology")
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 2)
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "HTFAC.HTFACLiteratureMicrobiology")
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 1)
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "HTFAC.HTFACLiteratureMicrobiology")
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.1)
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "HTFAC.HTFACLiteratureMicrobiology")
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.1)
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "HTFAC.HTFACLiteratureMicrobiology")
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 0.5)
table.insert(ProceduralDistributions.list["HospitalLockers"].items, "HTFAC.HTFACLiteratureMicrobiology")
table.insert(ProceduralDistributions.list["HospitalLockers"].items, 1)

--[------------------- HTFACLiteratureHematology -------------------]--
--For some reason this doesn't seem to work.
--table.insert(VehicleDistributions["Postal"].items, "HTFAC.HTFACLiteratureHematology")
--table.insert(VehicleDistributions["Postal"].items, 0.5)
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "HTFAC.HTFACLiteratureHematology")
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1)
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "HTFAC.HTFACLiteratureHematology")
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 2)
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "HTFAC.HTFACLiteratureHematology")
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 1)
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "HTFAC.HTFACLiteratureHematology")
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.1)
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "HTFAC.HTFACLiteratureHematology")
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.1)
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "HTFAC.HTFACLiteratureHematology")
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 0.5)
table.insert(ProceduralDistributions.list["HospitalLockers"].items, "HTFAC.HTFACLiteratureHematology")
table.insert(ProceduralDistributions.list["HospitalLockers"].items, 1)

--[------------------- HTFACLiteratureCadavers -------------------]--
--For some reason this doesn't seem to work.
--table.insert(VehicleDistributions["Postal"].items, "HTFAC.HTFACLiteratureCadavers")
--table.insert(VehicleDistributions["Postal"].items, 0.5)
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "HTFAC.HTFACLiteratureCadavers")
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1)
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "HTFAC.HTFACLiteratureCadavers")
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 2)
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "HTFAC.HTFACLiteratureCadavers")
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 1)
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "HTFAC.HTFACLiteratureCadavers")
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.1)
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "HTFAC.HTFACLiteratureCadavers")
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.1)
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "HTFAC.HTFACLiteratureCadavers")
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 0.5)
table.insert(ProceduralDistributions.list["PoliceDesk"].items, "HTFAC.HTFACLiteratureCadavers")
table.insert(ProceduralDistributions.list["PoliceDesk"].items, 2)
table.insert(ProceduralDistributions.list["HospitalLockers"].items, "HTFAC.HTFACLiteratureCadavers")
table.insert(ProceduralDistributions.list["HospitalLockers"].items, 1)

